---
- name: Set NMState managed cluster kubeconfig
  ansible.builtin.set_fact:
    managed_kubeconfig: "artifacts/kubeconfigs/{{ site_item.value.cluster_name }}.kubeconfig"

- name: Create NMState namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ managed_kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ nmstate.namespace }}"

- name: Create NMState OperatorGroup
  kubernetes.core.k8s:
    kubeconfig: "{{ managed_kubeconfig }}"
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: openshift-nmstate
        namespace: "{{ nmstate.namespace }}"
      spec:
        targetNamespaces:
          - "{{ nmstate.namespace }}"

- name: Subscribe to Kubernetes NMState Operator
  kubernetes.core.k8s:
    kubeconfig: "{{ managed_kubeconfig }}"
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: "{{ nmstate.subscription }}"
        namespace: "{{ nmstate.namespace }}"
      spec:
        channel: "{{ nmstate.channel }}"
        installPlanApproval: Automatic
        name: "{{ nmstate.subscription }}"
        source: "{{ nmstate.source }}"
        sourceNamespace: "{{ nmstate.source_namespace }}"

- name: Wait for NMState installedCSV
  kubernetes.core.k8s_info:
    kubeconfig: "{{ managed_kubeconfig }}"
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ nmstate.subscription }}"
    namespace: "{{ nmstate.namespace }}"
  register: nmstate_subscription
  until:
    - nmstate_subscription.resources | length == 1
    - nmstate_subscription.resources[0].status.installedCSV is defined
  retries: "{{ (wait.operator_seconds / 15) | int }}"
  delay: 15

- name: Wait for NMState CSV to succeed
  kubernetes.core.k8s_info:
    kubeconfig: "{{ managed_kubeconfig }}"
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ nmstate_subscription.resources[0].status.installedCSV }}"
    namespace: "{{ nmstate.namespace }}"
  register: nmstate_csv
  until:
    - nmstate_csv.resources | length == 1
    - nmstate_csv.resources[0].status.phase | default('') == 'Succeeded'
  retries: "{{ (wait.operator_seconds / 15) | int }}"
  delay: 15

- name: Create NMState singleton
  kubernetes.core.k8s:
    kubeconfig: "{{ managed_kubeconfig }}"
    state: present
    definition:
      apiVersion: nmstate.io/v1
      kind: NMState
      metadata:
        name: nmstate

- name: Wait for NodeNetworkState CRD
  kubernetes.core.k8s_info:
    kubeconfig: "{{ managed_kubeconfig }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: nodenetworkstates.nmstate.io
  register: nns_crd
  until: nns_crd.resources | length == 1
  retries: 60
  delay: 10
