---
- name: List existing phoenixNAP private networks
  ansible.builtin.uri:
    url: "{{ phoenixnap.api_base }}/networks/v1/private-networks"
    method: GET
    headers:
      Authorization: "Bearer {{ pnap_token }}"
    return_content: true
    status_code: 200
  register: pnap_private_networks_existing
  no_log: true

- name: Ensure a site-local private L2 network exists in each region
  ansible.builtin.include_tasks: site.yml
  loop: "{{ sites | dict2items }}"
  loop_control:
    loop_var: site_item
