---
- name: Provision phoenixNAP hourly iPXE servers
  hosts: localhost
  gather_facts: false
  roles:
    - role: pnap_auth
    - role: pnap_select_sku
      when: (phoenixnap.auto_select.enabled | bool) and (pnap_selected_skus is not defined)
    - role: pnap_servers
