---
- name: List existing phoenixNAP servers
  ansible.builtin.uri:
    url: "{{ phoenixnap.api_base }}/bmc/v1/servers"
    method: GET
    headers:
      Authorization: "Bearer {{ pnap_token }}"
    return_content: true
    status_code: 200
  register: pnap_servers_existing
  no_log: true

- name: Provision each SNO site
  ansible.builtin.include_tasks: site.yml
  loop: "{{ sites | dict2items }}"
  loop_control:
    loop_var: site_item
